# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://teachingresources.shaffermusic.com
title: "Teaching Resources, Music Theory and Aural Skills"
email: kris.shaffer@colorado.edu
description: "CU–Boulder College of Music"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/kshaffer/teachingresources
